### ISSUE TITLE
must replace right part of word at caret

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_console_complete#13]
dlg_proc(DLG_CTL<caret>_DELETE

choose DLG_CTL_HANDLE -> wrong result

**Comment by halfbrained** [comment]
Well Ok, but the behavior you are describing here as desirable was the worst thing about using SynWrite for me ... just so you know :)

**Comment by Alexey-T** [comment]
ed.complete has param `len2` -- count of word chars after caret to right.

**Comment by Alexey-T** [comment]
ahhhh. understood.

**Comment by Alexey-T** [comment]
let's add OPTION?
from settings/plugins.ini you can read one option

[cuda_complete_console]
replace_right_part=1

**Comment by Alexey-T** [comment]
@halfbrained If u don't want this behaviour, lets keep it as is, OK (you may close issue)

**Comment by halfbrained** [comment]
I added the option... but I had a thought: 


`canvas_pr<caret>handle  `
`DLG_<caret>CREATE`

There is no need to replace right part in first case, but should be replaced in second. So maybe I should just check if the whole part is the start of an existing identifier, and replace only in this case? If this is acceptable - no need for an option.

**Comment by Alexey-T** [comment]
> no need to replace right part in first case

needed in 1st too. if user dont want it, he must add  a space after caret (before ctrl+space). IMO
