### ISSUE TITLE
skip work in strings

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_console_complete#15]
s='dl<caret>www'

this must not give work. now it gives `dlg_` names!

**Comment by Alexey-T** [comment]
same for unclosed constants:

    s='d<caret>

**Comment by Alexey-T** [comment]
I can publish it now; and you fix this issue much later, ok? @halfbrained

**Comment by halfbrained** [comment]
Sorry, forgot to write. It is fixed now.
Still getting a hang of github :)
