### ISSUE TITLE
in config() always write your options, don't read them in config()

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_console_complete#17]
why do u read in config()?

**Comment by halfbrained** [comment]
If I open config(), change some value, save, then open config() again - values stored in plugin will overwrite changed value. So I write only if options are not present. Is it not a problem?

**Comment by halfbrained** [comment]
... but I suppose since I read new values on save() that is not a concern... I will remove it :D

**Comment by Alexey-T** [comment]
ah, very minor issue
