### ISSUE TITLE
globals from cuda_console_complete must not be in result

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_console_complete#21]
fn_config = os.path.join(app_path(APP_DIR_SETTINGS), 'plugins.ini')
SECTION = 'console_complete'

these globals also suggested! 
f[ctrl+space]
->
```
file_open
finder_proc
fn_config
```

**Comment by halfbrained** [comment]
Should be good now

**Comment by Alexey-T** [comment]
works good, tks. Upd in addons.
