### ISSUE TITLE
unneeded space char on Win10 (seems OK on linux)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_console_complete#24]
- type `=dlg`, ctrl+space
->
1. during autocmplete listbox show, I have text with space: `=dlg `.
2. after choosing dlg_color, I got `=ddlg_color()` - 2 d chars!

**Comment by halfbrained** [comment]
Had an unneeded `strip()`, it was from the first commit, I think it was to remove new-line character - removed it
