### ISSUE TITLE
are locals() get only 1 time?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_console_complete#9]
seems you get locals() on EVERY on_key?
```
      # get Console locals()
      Parcel._locals.clear()
      app_proc(PROC_EXEC_PYTHON, 'from cuda_cns_complete.cns_complete import Parcel; '+
            'Parcel._locals.update(locals())')
```

need 1 time! save them and re-use.

**Comment by halfbrained** [comment]
> seems you get locals() on EVERY on_key?  

A scary thought :D
No, it was on every Ctrl+Space, though locals gave a copy, fixed now.
